title: "Indian Star Formation Studies"
description: "Showcasing past conferences, events, and papers published by the Indian Star Formation Studies community."
hostname: "starformationindia.org"
baseurl: ""
theme: jekyll-theme-minimal
